### PR TITLE
Merge...

### PR DESCRIPTION
**Pull request by vbmithr**
Have a look… I think we should merge my fork. I changed the name to "nanomsg" though.
Keep me up to date.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Looks good. Does it make sense to rename the lib then? The `O` might be confusing now...

**Comment by rgrinberg** [comment]
I've added you as a collaborator as well.

**Comment by rgrinberg** [comment]
@vbmithr PS, how come cstruct was kicked out in favor of ccbigstring?

**Comment by vbmithr** [comment]
On 12/01/2015 20:19, Rudi Grinberg wrote:
> @vbmithr <https://github.com/vbmithr> PS, how come cstruct was kicked
> out in favor of ccbigstring?

Ah, I did this because I prefer the bigstring interface of containers,
(cstruct force to "make a cstruct out of a bigarray", and the functions
acts on cstruct which includes offset and length), whereas a simple
"bigstring" interface does not bundle the underlying string plus
offset/length together.


Moreover there is no camlp4 dependency in containers (and containers is
a cool lib IMO).

But cstruct was OK too. If you really have something against containers
we can always change.

Cheers,

-- 
Vincent

**Comment by avsm** [comment]
Cstruct does that primarily for speed -- slicing a bigarray is a very slow operation, and Cstruct consumers typically do it a lot (and is just an OCaml allocation in Cstruct's case).

**Comment by rgrinberg** [comment]
Both options are fine I'd say. Note that cstruct's camlp4 is optional now however.

**Pull request merged**
